# Uncomment this line to define a global platform for your project

platform :ios, ‘8.0'
source ‘https://github.com/CocoaPods/Specs.git'
use_frameworks!

target "BeaconServe" do

pod 'IQKeyboardManager'
pod 'RSTCoreDataKit'
pod 'PureLayout'
pod 'M13Checkbox'
pod 'RSTCoreDataKit'
pod 'CHCSVParser'
pod 'JLToast', '~> 1.3'

end